# common rules for all tests. The makefile that includes this must define
# SCC_ROOT_DIR, SCC_HAVE_FLAGS, TESTOBJ, OBJ and BIN.

include $(SCC_ROOT_DIR)/makefile.common
SRCDIR := $(SCC_ROOT_DIR)/src

# SDL libraries
LDFLAGS += -L$(SDL_LIB_DIR)
LDLIBS += -lSDL2
INCLUDE_DIRS += -I$(SDL_INCLUDE_DIR) -I$(SCC_ROOT_DIR)/include

ifneq (,$(findstring -DHAVE_SDL_IMAGE, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_image
endif
ifneq (,$(findstring -DHAVE_SDL_MIXER, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_mixer
endif
ifneq (,$(findstring -DHAVE_SDL_TTF, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_ttf
endif

# openGL libraries
ifneq (,$(HAVE_GL))
    LDFLAGS += -L$(GL_LIB_DIR)
    LDLIBS += -lGL
    EXTRA_INCLUDE_DIRS += -I$(GL_INCLUDE_DIR)
endif
ifneq (,$(HAVE_GLEW))
    LDFLAGS += -L$(GLEW_LIB_DIR)
    LDLIBS += -lGLEW
    EXTRA_INCLUDE_DIRS += -I$(GLEW_INCLUDE_DIR)
endif

DEBUG = -g

# for make recursive calls
export SCC_HAVE_FLAGS
export EXTRA_INCLUDE_DIRS
export DEBUG

OBJPATH := $(addprefix $(OBJDIR)/, $(OBJ))

CXXFLAGS := $(INCLUDE_DIRS) $(EXTRA_INCLUDE_DIRS) $(DEBUG) -std=c++11 \
	$(SCC_HAVE_FLAGS)

$(BIN) : $(OBJPATH) $(TESTOBJ)
	$(CXX) -o $(BIN) $^ $(LDFLAGS) $(LDLIBS)

$(TESTOBJ) : $(TESTOBJ:.o=.cpp)
	$(CXX) -c -o $@ $^ $(CXXFLAGS)

$(OBJPATH) :
	$(MAKE) -C $(SRCDIR) $@

clean:
	rm -f $(TESTOBJ)
	$(MAKE) -C $(SRCDIR) clean

.PHONY: clean
