# common rules for all tests. The makefile that includes this must define
# SCC_ROOT_DIR, SCC_HAVE_FLAGS, TESTOBJ and BIN.

include $(SCC_ROOT_DIR)/tests/makefile.common

# SDL libraries
LDFLAGS += -L$(SDL_LIB_DIR)
LDLIBS += -lSDL2
INCLUDE_DIRS += -I$(SDL_INCLUDE_DIR) -I$(SCC_ROOT_DIR)/include

ifneq (,$(findstring -DHAVE_SDL_IMAGE, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_image
endif
ifneq (,$(findstring -DHAVE_SDL_MIXER, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_mixer
endif
ifneq (,$(findstring -DHAVE_SDL_TTF, $(SCC_HAVE_FLAGS)))
    LDLIBS += -lSDL2_ttf
endif

ifneq (,$(HAVE_GL))
    INCLUDE_DIRS += -I$(GL_INCLUDE_DIR)
    LDFLAGS += -L$(GL_LIB_DIR)
    LDLIBS += -lGL
endif
ifneq (,$(HAVE_GLEW))
    INCLUDE_DIRS += -I$(GLEW_INCLUDE_DIR)
    LDLIBS += -lGLEW
endif

CXXFLAGS := $(INCLUDE_DIRS) -g -std=c++11 $(SCC_HAVE_FLAGS)

$(BIN) : $(TESTOBJ)
	$(CXX) -o $(BIN) $^ $(LDFLAGS) $(LDLIBS)

$(TESTOBJ) : $(TESTOBJ:.o=.cpp)
	$(CXX) -c -o $@ $^ $(CXXFLAGS)

clean:
	rm -f $(TESTOBJ)

.PHONY: clean
