SCC_ROOT_DIR := ../../..
SCC_HAVE_FLAGS := -DUSE_GL_CLASSES

HAVE_GL := "yes"
HAVE_GLEW := "yes"

TESTOBJ := main.o
OBJ := window.o glcontext.o renderer.o texture.o vertexarray.o buffer.o
BIN := vaoAndVbo

include $(SCC_ROOT_DIR)/tests/makefile.tests
