SCC_ROOT_DIR := ../../..
SCC_HAVE_FLAGS :=

# they could be any non-empty string really
HAVE_GL := "yes"
HAVE_GLEW := "yes"

TESTOBJ := main.o
OBJ := window.o glcontext.o renderer.o texture.o
BIN := drawTriangle

include $(SCC_ROOT_DIR)/tests/makefile.tests
