SCC_ROOT_DIR = ../..

# comment/uncomment the -D flags below to test
SCC_HAVE_FLAGS = \
                     # -DHAVE_SDL_IMAGE \
                     # -DHAVE_SDL_TTF \
                     # -DHAVE_SDL_MIXER
TESTOBJ = main.o
BIN = configTest

include $(SCC_ROOT_DIR)/tests/makefile.tests
