SCC_ROOT_DIR := ../../../..
SCC_HAVE_FLAGS := -DUSE_GL_CLASSES

HAVE_GL := "yes"
HAVE_GLEW := "yes"

TESTOBJ := main.o
OBJ := window.o glcontext.o renderer.o texture.o gltexture.o surface.o rwops.o
BIN := image2DFromSurface

include $(SCC_ROOT_DIR)/tests/makefile.tests
