SCC_ROOT_DIR := ../../..
SCC_HAVE_FLAGS := -DHAVE_SDL_IMAGE -DHAVE_SDL_TTF

TESTOBJ := main.o
OBJ := window.o renderer.o texture.o truetypefont.o surface.o rwops.o
BIN := fromText

include $(SCC_ROOT_DIR)/tests/makefile.tests
